# Generated by Django 4.2.5 on 2023-10-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestrsvp',
            name='food_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.fooditem'),
        ),
    ]
