# Generated by Django 4.2.5 on 2023-11-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_alter_event_rsvp_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rsvp',
        ),
    ]
