# Generated by Django 4.2.5 on 2023-11-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_remove_event_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
