# Generated by Django 4.2.5 on 2023-10-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuestRSVP',
            fields=[
                ('rsvp_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('food_choice', models.CharField(max_length=50)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PartyProBE.event')),
            ],
            options={
                'unique_together': {('event_id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
                ('rsvp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PartyProBE.guestrsvp')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('names', models.CharField(max_length=50)),
                ('ratings', models.CharField(max_length=50)),
                ('reviews', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('testimonials_id', models.AutoField(primary_key=True, serialize=False)),
                ('rsvp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PartyProBE.guestrsvp')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PartyProBE.users')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyProBE.guestrsvp'),
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyProBE.users'),
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('event', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('food', models.CharField(max_length=200)),
                ('dessert', models.CharField(max_length=50)),
                ('number_of_guest', models.CharField(max_length=50)),
                ('alcohol', models.CharField(max_length=50)),
                ('other', models.CharField(max_length=10)),
                ('catering_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PartyProBE.event')),
                ('rsvp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PartyProBE.guestrsvp')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('rsvp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyProBE.guestrsvp')),
                ('testimonials_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyProBE.testimonials')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyProBE.users')),
            ],
        ),
    ]
