# Generated by Django 4.2.5 on 2023-10-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyProBE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catering',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='catering',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='catering',
            name='food',
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
                ('dessert', models.CharField(max_length=50)),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='PartyProBE.catering')),
            ],
        ),
    ]
