# Generated by Django 4.2.5 on 2023-10-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyProBE', '0002_remove_catering_alcohol_remove_catering_dessert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='PartyProBE.catering'),
        ),
    ]
