# Generated by Django 4.2.5 on 2023-10-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyProBE', '0002_alter_users_catering_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='catering_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PartyProBE.catering'),
        ),
    ]
