# Generated by Django 4.2.5 on 2023-10-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyProBE', '0003_alter_users_catering_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='catering_id',
            field=models.CharField(max_length=50),
        ),
    ]
