# Generated by Django 4.2.5 on 2023-10-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyProBE', '0004_alter_users_catering_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='catering_id',
        ),
    ]
