# Generated by Django 4.2.5 on 2023-10-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyProBE', '0005_remove_catering_event_id_remove_users_event_id_and_more'),
        ('PartyProBE', '0005_remove_users_catering_id'),
    ]

    operations = [
    ]
